@startuml
'https://plantuml.com/class-diagram

interface DataRepository {
+retrieve_datas(scenario: Scenario)
+retrieve_data(scenario: Scenario)
}

class CompositeDataRepository

class OHLCVDataRepository

interface TickerFeedRepository
class NewsFeedRepository
class StockTweetsFeedRepository
class SentimentDataRepository

CompositeDataRepository -up-|> DataRepository
OHLCVDataRepository -up-|> DataRepository
SentimentDataRepository -up-|> DataRepository

CompositeDataRepository -up-> DataRepository

TickerFeedRepository <|-- NewsFeedRepository
TickerFeedRepository <|-- StockTweetsFeedRepository
SentimentDataRepository --> TickerFeedRepository

@enduml