@startuml
'https://plantuml.com/class-diagram
title
DataRepository data flow

end title

object DataRepository
object OHLCVDataRepository
object NewsMediaRepository
object NewsSentimentDataRepository
object StockTweetsMediaRepository
object StockTweetsSentimentDataRepository
diamond mergeData


OHLCVDataRepository --> mergeData

NewsMediaRepository --> NewsSentimentDataRepository
NewsSentimentDataRepository --> mergeData

StockTweetsMediaRepository --> StockTweetsSentimentDataRepository
StockTweetsSentimentDataRepository --> mergeData

mergeData --> DataRepository

@enduml