@startuml
'https://plantuml.com/class-diagram

class DataRepository {
+retrieve_datas(scenario: Scenario)
+retrieve_data(scenario: Scenario)
}

class CompositeDataRepository

class OHLCVDataRepository
class TechnicalIndicatorsDataFilter

class ArticleDataRepository
class NewsDataRepository
class StockTweetsDataRepository
class SentimentAnalyzer
class SentimentIndicatorDataFilter

CompositeDataRepository -up-|> DataRepository
OHLCVDataRepository -up-|> DataRepository
ArticleDataRepository -up-|> DataRepository

CompositeDataRepository -up-> DataRepository

TechnicalIndicatorsDataFilter -right-> OHLCVDataRepository

ArticleDataRepository <|-- NewsDataRepository
ArticleDataRepository <|-- StockTweetsDataRepository
ArticleDataRepository --> SentimentAnalyzer
ArticleDataRepository --> SentimentIndicatorDataFilter
@enduml